language: python

python:
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - nvm install node && git clone "https://github.com/mozilla/send.git" && cd send && npm install && npm start &
  - pip install .

script:
  - pytest
  - send-cli -h
